name: aljawad_services_app
description: "التطبيق الرسمي لشركة الجواد الدولية العربية - AL-Gawad Group"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0B1B3D"
  adaptive_icon_foreground: "assets/logo/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/logo/
    - assets/images/hero/
    - assets/images/services/
    - assets/images/projects/
    - assets/images/placeholders/
